### ISSUE TITLE
TypeError: unhashable type: 'Interface'

### ISSUE THREAD

**Issue by chcorbato** [ipa-led/ros_graph_parser#4]
Hi,

I have tried to run `yaml_snapshot` but I get the following error:
```
$ rosrun ros_graph_parser yaml_snapshot mros_reasoner.yaml
Traceback (most recent call last):
  File "/home/chcorbato/abb_mros/src/ros_graph_parser/scripts/yaml_snapshot", line 15, in <module>
    snapshot = rg.create_ros_graph_snapshot()
  File "/home/chcorbato/abb_mros/src/ros_graph_parser/src/ros_graph_parser/snapshot.py", line 62, in create_ros_graph_snapshot
    node.publishers.add(rg.Interface(pub, topics_dict[pub]))
TypeError: unhashable type: 'Interface'
```
Not sure if I'm doing something wrong.

**Comment by dhled** [comment]
I'm also a bit curious and I don't know where to start. I will try to get more debug print. I will update this asap.

**Comment by trn84** [comment]
any updates?
